Name : Abhijeet Jadhav 

Branch : CO

# numpy Function

In [6]:
import numpy as abhi
arr=abhi.array([1,2,3,4,5])

In [5]:
arr

array([1, 2, 3, 4, 5])

# 1. Sort 

In [7]:
new_arr= abhi.array([12,3,1,4,5,6])

In [9]:
abhi.sort(new_arr)

array([ 1,  3,  4,  5,  6, 12])

# 2. Clip

In [11]:
abhi.clip(arr, 2, 4)

array([2, 2, 3, 4, 4])

# 3. Round 

In [12]:
arr1=abhi.array([1.223,2.367])

In [14]:
abhi.round(arr1,1)

array([1.2, 2.4])

# 4.Floor 

In [16]:
arr2=abhi.array([1.2, 2.8, 4.5, 3.1, 67.9, 89.3, 10.7])

In [18]:
abhi.floor(arr2)

array([ 1.,  2.,  4.,  3., 67., 89., 10.])

# 5. Ceil 

In [20]:
arr2

array([ 1.2,  2.8,  4.5,  3.1, 67.9, 89.3, 10.7])

In [22]:
abhi.ceil(arr2)

array([ 2.,  3.,  5.,  4., 68., 90., 11.])

# 6. Intersect

In [24]:
a = abhi.array([1, 2, 3])
b = abhi.array([3, 4, 5])

abhi.intersect1d(a, b)    # [3]

array([3])

# 7. union

In [26]:
abhi.union1d(a, b)  

array([1, 2, 3, 4, 5])

# 8. Set difference

In [28]:
abhi.setdiff1d(a, b)

array([1, 2])

# 9. Sum

In [30]:
arr3=abhi.array([10,20,30,40,50])

In [34]:
abhi.sum(arr3)

np.int64(150)

# 10. Product

In [36]:
arr4= abhi.array([5,4,3,2,1])

In [37]:
abhi.prod(arr4)

np.int64(120)